project:
    type: tufte
book:
  open-graph: true
  site-url: https://georgiadoing.github.io/tufte-quarto/
  repo-url: https://github.com/georgiadoing/tufte-quarto/
  repo-actions: [edit, issue]
  title: |
    Course: CSC:XXX Course Title\
    Documentation
  title-short: CSCXXX # title-short is used in the pdf head
  output-file: CSCXXXNotes # outputs: docs/TufteStyledBook.pdf
  author: Georgia Doing
  publisher: self
  date-format: MMMM, YYYY
  license: "CC BY"
  chapters:
    - index.qmd
    - 02-Main/schedule.qmd
    - 02-Main/resources.qmd
    - 02-Main/syllabus.qmd
    - 02-Main/grading.qmd
    - part: Assignments
      chapters:
        - 03-Assignments/final_project.qmd
    - part: Weekly Notes
      chapters:
        - 04-Notes/week1.qmd
        - 04-Notes/week2.qmd
        - 04-Notes/week3.qmd
        - 04-Notes/week4.qmd
        - 04-Notes/week5.qmd
        - 04-Notes/week6.qmd
        - 04-Notes/week7.qmd
        - 04-Notes/week8.qmd
        - 04-Notes/week9.qmd
        - 04-Notes/week10.qmd
    - part: about.qmd
      chapters:
        - 03-Back/references.qmd
        - 03-Back/ack.qmd
        - 03-Back/colophon.qmd
bibliography: references.bib
